url: https://emo-sci.github.io/
baseurl: /web/

# Site settings
title: EMO-SCI
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Prof. Dr. Stefan Dietze
  pic: 1
  position: Project Owner
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/stefandietze/
    - title: bluesky
      url: https://bsky.app/profile/dietzestefan.bsky.social
    - title: globe
      url: https://stefandietze.wordpress.com

- name: Prof. Dr. Konstantin Todorov
  pic: 2
  position: Project Owner
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/konstantin-todorov-7b79ab3ab/
    - title: globe
      url: https://www.lirmm.fr/konstantin-todorov/

- name: Prof. Dr. Achim Rettinger
  pic: 3
  position: Project Owner
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/achim-rettinger/
    - title: globe
      url: https://www.uni-trier.de/universitaet/fachbereiche-faecher/fachbereich-ii/faecher/computerlinguistik-und-digital-humanities/team/prof-dr-achim-rettinger

- name: Dr. Marc Feger
  pic: 4
  position: Senior Researcher
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/marc-feger/
    - title: globe
      url: https://www.marc-feger.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty