url: https://emo-sci.github.io/
baseurl: /web/

# Site settings
title: EMO-SCI
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:

- name: Prof. Dr. Konstantin Todorov
  pic: 2
  position: Project Owner
  social:
    - title: linkedin
      family: brands
      url: https://www.linkedin.com/in/konstantin-todorov-7b79ab3ab/
    - title: globe
      family: solid
      url: https://www.lirmm.fr/konstantin-todorov/

- name: Prof. Dr. Stefan Dietze
  pic: 1
  position: Project Owner
  social:
    - title: linkedin
      family: brands
      url: https://www.linkedin.com/in/stefandietze/
    - title: bluesky
      family: brands
      url: https://bsky.app/profile/dietzestefan.bsky.social
    - title: globe
      family: solid
      url: https://stefandietze.wordpress.com

- name: Prof. Dr. Achim Rettinger
  pic: 3
  position: Project Owner
  social:
    - title: linkedin
      family: brands
      url: https://www.linkedin.com/in/achim-rettinger/
    - title: globe
      family: solid
      url: https://www.uni-trier.de/universitaet/fachbereiche-faecher/fachbereich-ii/faecher/computerlinguistik-und-digital-humanities/team/prof-dr-achim-rettinger

- name: Dr. Salim Hafid
  pic: 7
  position: Postdoctoral Researcher
  social:
    - title: linkedin
      family: brands
      url: https://linkedin.com/in/salimhafid1
    - title: globe
      family: solid
      url: https://salim-hafid.github.io/

- name: Dr. Marc Feger
  pic: 4
  position: Postdoctoral Researcher
  social:
    - title: linkedin
      family: brands
      url: https://www.linkedin.com/in/marc-feger/
    - title: globe
      family: solid
      url: https://www.marc-feger.com

- name: Florencia Brunello
  pic: 5
  position: PhD Student
  social:
    - title: linkedin
      family: brands
      url: https://www.linkedin.com/in/florenciabrunello/
    - title: github
      family: brands
      url: https://github.com/florbrunello

- name: Nils Schwager
  pic: 8
  position: PhD Student
  social:
    - title: linkedin
      family: brands
      url: https://www.linkedin.com/in/nils-schwager/
    - title: globe
      family: solid
      url: https://nsschw.github.io

- name: Vetea Jacot
  pic: 6
  position: PhD Student
  social:
    - title: gitlab
      family: brands
      url: https://framagit.org/Vetea_Jacot

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    family: brands
    url: https://github.com/EMO-SCI
  - title: a
    family: solid
    url: https://anr.fr/en/funded-projects-and-impact/funded-projects/project/funded/project/b2d9d3668f92a3b9fbbf7866072501ef-8808056006/?tx_anrprojects_funded%5Bcontroller%5D=Funded&cHash=77922bf7aa6c22801ac191e3f7af14b6
  - title: g
    family: solid
    url: https://gepris.dfg.de/project/569156112?lang=en

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty